---
title: "ggplot2"
author: "Geonwoo Ban"
date: '2021 6 30 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Visualization with mpg data set

```{r}
data(mpg)
#?mpg
mpg %>% summary()
```

* 변수 type 확인하기

* 변수의 성질을 고려하지 않은 그림은 오히려 역효과

* 성질을 잘 파악하고 적재적소에 맞는 시각화를 하는 것이 매우 중요

* 항상 마인드는 비전공자가 본다는 생각으로 최대한 직관적으로 시각화하기


\newpage

> conti vs conti

1. displ : 차의 엔진 사이즈

2. hwy : 고속도로 연비

```{r}
mpg %>% 
  ggplot()+geom_point(aes(x=displ, y=hwy))
```

\newpage

> conti vs categorical

1. hwy : 고속도로 연비

2. cyl : 실린더 개수

```{r}
mpg %>% 
  ggplot()+geom_point(aes(x=hwy, y=cyl))
```


```{r}
mpg %>% 
  ggplot()+geom_boxplot(aes(x=hwy, y=cyl, group=cyl))
```

```{r}
mpg %>% 
  ggplot()+geom_boxplot(aes(x=hwy, y=factor(cyl), group=factor(cyl)))
```

\newpage

> cate vs cate

1. class : 차종

2. drv : 전륜, 후륜, 사륜

```{r}
mpg %>% 
  ggplot()+geom_point(aes(x=class, y=drv))
```

```{r}
mpg %>% 
  ggplot(aes(x=class, y=drv))+
  geom_count()


mpg %>% 
  count(class, drv) %>% 
  ggplot(aes(x=class, y=drv))+
  geom_tile(aes(fill=n))
```

\newpage

> coloring

```{r}
mpg %>% 
  ggplot()+geom_point(aes(x=displ, y=hwy, color=displ<5))

mpg %>% 
  ggplot()+
  geom_point(aes(x=displ, y=hwy, color=class))
```

\newpage

> facet

```{r}
mpg %>% 
  ggplot()+
  geom_point(aes(x=displ, y=hwy))+
  facet_wrap(~class, nrow=5)

mpg %>% 
  ggplot()+
  geom_point(aes(x=displ, y=hwy))+
  facet_grid(~class)

mpg %>% 
  ggplot()+
  geom_point(aes(x=displ, y=hwy))+
  facet_grid(class~.)

mpg %>%
  ggplot()+
  geom_point(aes(x = displ, y = hwy))+
  facet_grid(drv~cyl)
```

\newpage

> soomth line

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, colour = drv)) +
  geom_point() +
  geom_smooth(se = FALSE)
```







































